# Master configuration file for RISK
# ==================================

input:
  network-filepath: /Users/irahorecka/Desktop/Harddrive_Desktop/PhD/University of Toronto/Rost Lab/GitHub/risk/data/cytoscape/metabolic-enrichment-network-2024feb-1m.cys
  annotation-filepath: /Users/irahorecka/Desktop/Harddrive_Desktop/PhD/University of Toronto/Rost Lab/GitHub/risk/data/json/total_fm_2024Feb.json
  # network-filepath: /Users/irahorecka/Desktop/Harddrive_Desktop/PhD/University of Toronto/Rost Lab/GitHub/risk/data/cytoscape/gene_x_gene_cytoscape.cys
  # annotation-filepath: /Users/irahorecka/Desktop/Harddrive_Desktop/PhD/University of Toronto/Rost Lab/GitHub/risk/data/json/500_modules_annotation_file.json


network:
  properties:
    random-seed: 888
    node:
      source-label: source
      target-label: target
      min-edges: 0
    edge:
      weight-label: weight

  enrichment:
    compute-sphere: true # OPTIONS: true, false
    dimple-factor: 12 # OPTIONS: auto || Any integer from 0 to 1000
    include-edge-weight: true # OPTIONS: true, false
    null-distribution: network # OPTIONS: network, annotation
    type: permutation
    num-permutations: 1000
    direction: highest  # OPTIONS: Enrichment direction: highest, lowest
    min-cluster-size: 5 # Minimum final cluster membership size - suggested to omit small clusters
    pval-cutoff: 0.01
    apply-fdr: true  # OPTIONS: true, false
    fdr-cutoff: 0.9999

  node:
    neighborhood-distance-metric: shortpath # OPTIONS: affinity_propagation, euclidean, louvain, shortpath
    neighborhood-distance-louvaine-resolution: 0.1
    neighborhood-score-metric: variance  # OPTIONS: sum, variance, zscore
    neighborhood-diameter: 1.00 # OPTIONS: Any value between 0 to 1
    group-distance-criterion: distance # OPTIONS: distance, maxclust
    group-distance-linkage: average # OPTIONS: auto || single, complete, average, weighted, centroid, median, ward
    group-distance-metric: cosine # OPTIONS: auto || braycurtis, canberra, chebyshev, cityblock, correlation, cosine, dice, euclidean, hamming, jaccard,
    # jensenshannon, kulczynski1, mahalanobis, matching, minkowski, rogerstanimoto, russellrao, seuclidean, sokalmichener, sokalsneath, sqeuclidean, yule
    # TODO: Fix below to be a bool
    unimodality-type: connectivity
